openapi: "3.0.0"
info:
  title: "Ethereum Tracker API"
  description: "API for tracking Ethereum wallet transactions and gas fees expenses"
  version: "1.0.0"

tags:
  - name: "result"
    description: "Get balance, transactions, total fees spent"

paths:
  /result:
    get:
      tags:
        - "result"
      summary: "Get balance, transactions, total fees spent"
      parameters:
        - name: "address"
          in: "query"
          schema:
            type: "string"
          required: true
          description: "Ethereum address"
        - name: "chains"
          in: "query"
          schema:
            type: "string"
          required: true
          description: "Chains id's separated by comma"
      responses:
        "200":
          description: "Successful response - returns an HTML page"
          content:
            text/html:
              schema:
                type: "string"
