name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t yurius007/ethertrac-flask:1.01.RELEASE .

      - name: Push Docker image to Docker Hub
        run: docker push yurius007/ethertrac-flask:1.01.RELEASE

      # - name: Deploy to EC2 via SSH
      #   env:
      #     PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     HOST: ${{ secrets.EC2_HOST }}
      #     USER: ${{ secrets.EC2_USER }}
      #   run: |
      #     echo "$PRIVATE_KEY" > private_key.pem
      #     chmod 600 private_key.pem
      #     ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
      #       ./deploy.sh
      #     EOF
      #     rm -f private_key.pem
